### ISSUE TITLE
Any player can "Block"

### ISSUE THREAD

**Issue by p-d-moore** [njustesen/ffai#10]
Currently, any player on the moving side that has yet to move can make a "Block" action.  This includes prone players and players that are not next to an opponent.  The "Block" button should be removed for any player that does not have a standing adjacent opponent AND for any player that themselves is prone and does not have the jump up skill.

**Comment by njustesen** [comment]
I was not able to verify this. Please show an example or describe how to reproduce.
<img width="212" alt="Screenshot 2019-03-30 at 14 55 35" src="https://user-images.githubusercontent.com/1433421/55277115-ed6b9e00-52fc-11e9-9f80-9f35203beb2c.png">
<img width="205" alt="Screenshot 2019-03-30 at 15 04 49" src="https://user-images.githubusercontent.com/1433421/55277141-3b80a180-52fd-11e9-9c60-4deb913fa0f7.png">

**Comment by p-d-moore** [comment]
I fixed that one already.

**Comment by njustesen** [comment]
Thanks
