### ISSUE TITLE
throw team-mate with ball scatters ball after successful landing

### ISSUE THREAD

**Issue by derNarr** [njustesen/ffai#146]
After throwing a team mate, which holds the ball, the ball is scattered after successful landing. If I understand the 2016 rules correctly, the thrown team mate should still hold the ball after successful landing.

![ball_bounce_after_successful_landing](https://user-images.githubusercontent.com/739332/121183358-454ea980-c864-11eb-9dd5-eb6260ced0a5.png)
![ball_bounce_board](https://user-images.githubusercontent.com/739332/121183373-4a135d80-c864-11eb-98cc-2cb0c238df5b.png)

The following test case succeeds, which puzzles me a little bit::

```

def test_successful_landing_with_ball():
    game = get_game_turn()
    team = game.get_agent_team(game.actor)
    game.clear_board()
    passer = team.players[0]
    passer.role.skills = []
    passer.role.ag = 2
    passer.extra_skills = [Skill.THROW_TEAM_MATE]
    game.put(passer, Square(1, 1))
    right_stuff = team.players[1]
    right_stuff.role.skills = []
    right_stuff.extra_skills = [Skill.RIGHT_STUFF]
    right_stuff_position = Square(2, 1)
    game.put(right_stuff, right_stuff_position)
    ball = Ball(right_stuff_position)
    game.put(ball, right_stuff_position)
    ball.is_carried = True
    game.put(right_stuff, right_stuff_position)
    game.step(Action(ActionType.START_PASS, player=passer))
    D6.fix(6)  # Accurate pass
    D8.fix(5)  # Forward scatter
    D8.fix(5)  # Forward scatter
    D8.fix(5)  # Forward scatter
    D6.fix(6)  # Land
    game.step(Action(ActionType.PICKUP_TEAM_MATE, player=passer, position=right_stuff.position))
    assert right_stuff.state.in_air
    target_square = Square(5, 5)
    game.step(Action(ActionType.THROW_TEAM_MATE, player=passer, position=target_square))
    assert game.has_report_of_type(OutcomeType.INACCURATE_PASS)  # Always inaccurate
    assert not game.has_report_of_type(OutcomeType.TURNOVER)
    assert game.has_report_of_type(OutcomeType.SUCCESSFUL_LAND)
    assert not game.has_report_of_type(OutcomeType.TURNOVER)
    assert passer.state.used
    assert not right_stuff.state.used
    landing_square = Square(target_square.x + 3, target_square.y)
    assert right_stuff.position == landing_square
    assert right_stuff.state.up
    assert ball.is_carried
    assert ball.position == landing_square
```

**Comment by mrbermell** [comment]
What you describe is correct. If the thrown player lands successfully the ball shouldn't bounce. 

I think the test is correct, after the throw it asserts that the ball is carried and that the ball is in the same position as the thrown player. 

Can got elaborate the problem?

**Comment by derNarr** [comment]
Yes, that was what puzzled me. I had hoped to get the same behaviour with the test as in the screenshot, but it do passes and I triple checked even with some additional calls to ``game.step``. The test and the screenshots come from the same branch (I checked that as well). For now I have to do other things, but if I find something in this respect, I will post it here.

**Comment by njustesen** [comment]
The test makes an accurate pass but the screenshot says inacurrate. Maybe that's the difference?

**Comment by mrbermell** [comment]
I read some code. I think the problem is in the Land-procedure. 

This line adds Bounce-procedure to the stack even if it's a successful landing when the thrown player is holding the ball. 
https://github.com/mrbermell/ffai/blob/91bc543afc2c6ee5a72b6f2ec1dc93048353791f/ffai/core/procedure.py#L2168

**Comment by njustesen** [comment]
You are right. Now it correctly bounces the ball if you land on it but also if you are carrying it.
We should change the if-statement to this:
`
elif self.game.get_ball_position() == self.player.position and game.get_ball().is_carried.
`
Would someone be up for changing this and adding test?

**Comment by derNarr** [comment]
If the player is landing on the ball the ball should Bounce, but if the player is landing on the ball and is holding the ball the should not Bounce, am I right?

Therefore adding 

I could not find anything telling what happens if a player lands on the ball. At least in the NAF FAQ this case is not covered, neither is it in the German 2016 rule book:

https://www.thenaf.net/blood-bowl/rules/clarifications/#10

The most reasonable thing is to bounce the ball if, you land on it.

I still don't get why the test above succeeds.

**Comment by derNarr** [comment]
In BB2020 you can throw a teammate even if it stunned or lying, but the "right stuff" is bouncing once and has to make an AV roll and there are different modifiers for landing depending on the throw team mate roll. But they don't say anything explicit about landing on the ball (again in the German rule book), but they say that if successfully landed the player is "freiwillig bewegt", which is the condition you need to be able to pick up the ball. If you don't land successfully the player counts as "unfreiwillig bewegt", which is the condition to bounce the ball.

In BB2016 below picking up the ball, landing on the ball is a condition to bounce the ball. (Yet another difference between BB2016 and BB2020, which I was not aware of yet.)

**Comment by derNarr** [comment]
I do create the test and I do realize, why the test above succeeds:

I create a new ball with ``ball = Ball(right_stuff_position)`` but I should get the ball from the game with ``ball = game.get_ball()``.
