### ISSUE TITLE
Illegal setup for team with less than 3 players causes death loop

### ISSUE THREAD

**Issue by p-d-moore** [njustesen/ffai#15]
When a team is reduced to less than 3 players, a legal setup is now longer possible.  The "step" function returns False in this case, and the setup is repeated.

Correct behaviour I believe is to either to reward touchdowns and advance the clock or to forfeit the game.  In any case, games currently enter an invalid state and can't progress.

**Comment by Khrog** [comment]
Well, technically you can field a team of 1.  They must be on the line.  So probably the correct solution is to check for number of team members and set the minimum number of players on the line to MIN(active players, 3)

**Comment by p-d-moore** [comment]
Indeed.  According to Living Rulebook 5:

"If you cannot set up 3 players on the Line of Scrimmage you must either concede the match (see page 15 (or page 29 if you are using the Extra Rules)), or carry on playing by placing as many players on the line of scrimmage as possible".  There is an additional rule somewhere related to not being able to field any players at all, in which case touchdowns are awarded and the clock is advanced (I believe by 2 turns) and KOs are rolled again.

**Comment by njustesen** [comment]
I have implemented Kzarik's suggestion.
In the special case of no active players at all, I think the game will just continue with just one player setting up.
