### ISSUE TITLE
When setting up for a kickoff some players can be prone

### ISSUE THREAD

**Issue by DrRerNate** [njustesen/ffai#40]
When setting up for a kickoff, sometimes some of the players are set up in a prone state (up=false). It is not just a display issue, the player is actually prone and needs to get up as his first action. I think this might happen when a player is stunned when a touchdown is scored or the half ends, leading him to "still be prone next turn." This, however, is not the correct behavior.

I added the line "player.state.reset()" to the methods reserves_to_pitch and pitch_to_reserves in ffai/core/game.py and that seems to solve the problem, but I couldn't track down what causes the problem exactly, so I can't be sure.

![Screenshot from 2019-07-29 21-29-00](https://user-images.githubusercontent.com/37294465/62124050-8e795e00-b2c9-11e9-8ed6-42f74eaa3ec4.png)

![Screenshot from 2019-07-29 21-29-31](https://user-images.githubusercontent.com/37294465/62124621-faa89180-b2ca-11e9-9ee7-444d28e11c6d.png)

**Comment by njustesen** [comment]
I think this has been fixed.
It occurred when knocked out players re-entered the game.
I will close this, but please reopen if it still happens.
