### ISSUE TITLE
Change pathfinding to use 2-dimensional cost

### ISSUE THREAD

**Issue by tysen2k** [njustesen/ffai#69]
I don’t know python at all, so this is just a suggestion that might be worthwhile to implement.

I propose modifying the A* pathfinding function to incorporate 2-dimensional costs (distance, risk).  Instead of returning a single optimal path, it would return a list of pareto optimal paths.  Basically, each path in the final result would be the lowest risk path for different movement allowance used.  That way the AI could choose between a path that takes 6 movement and 100% success verses one with 2 movement and 50% success.  This method would only need to be run once per player and cover both blitzing and non-blitzing moves.  Non-blitzing moves would always choose the least risk option regardless of movement, but blitzing moves would be able to pick from a variety of options.

For ease of implementation, you can transform the risk cost into a log-risk and precompute them for 2+, 3+, etc. for efficiency.  Instead of measuring risk as p, you would measure it as -log(p) and then risks become additive instead of multiplicative.

**Comment by p-d-moore** [comment]
For the sake of completeness, yes this can be done.  In addition, the path-finding can be updated to also handle leap moves (when leap is implemented).  The current calculation is already too slow, so I will first try and speed it up.

For the risk calculation, -log(p) works, but may not really add improve the speed of the calculation all that much - I don't believe that is the bottleneck but I can run some tests to be sure.

**Comment by tysen2k** [comment]
Agreed that speeding it up is the most important thing since it's part of the innermost loop.  Looking over the pathfinding code, it looks like there's a couple areas for improvement:

This part of the code could be time consuming:
`cost = math.sqrt(float(dx*dx+dy*dy))`
There's no reason that distances from every square on the pitch to every other square couldn't be precalculated.  Then it would be just a lookup table that holds distance[from][to].  That's just a 390x390 table and would speed things up a lot.

There's also no reason to check all 8 neighbors for every step, except for the very first step.  If the previous step was north, there is no reason to check any direction other than N, NE, or NW.  Again, this can be precomputed giving 3 possible current directions for each of the 8 prior directions.

**Comment by p-d-moore** [comment]
I will try doing some code profiling, but I don't think that the mathematical calcuations are the bottle neck.

As for which neighbours to check, admittedly my implementation is quite lazy and can probably be sped up, but it is definitely true that indirect paths are sometimes better.  The basic reason I went with brute force is that the cost is calculated using probability, and is very much path dependent.  Often in blood bowl, the lowest "cost" move to an adjacent square happens by moving to a different square first.  E.g. moving a player from a square adjacent an opponent to another square adjacent an opponent is often best done by dodging away first.  This is different from traditional A* path finding which requires an admissible heuristic function (one where an indirect path path is never lower cost).

**Comment by tysen2k** [comment]
Yep, you're right that it might require more than 3 neighbors.  I was thinking that a dodge into a square with 2 TZ was always the same no matter where you came from, but I see now that it can easily matter.

**Comment by p-d-moore** [comment]
So I used the very nice python program SnakViz to code profile a game of Grodbot vs Grodbot.   Pathfinding is about 40% of the total run cost.  Underneath that, the functions "get_tackle_zones_detailed_at" and "num_tackle_zones_at" are about half of that cost.  Optimising any other part of the pathfinding would be premature.

Incidentally, the function "potential_pass_actions" of the Grodbot takes as much time as the pathfinding, despite being relatively infrequently, so that is something else for to look at.

**Comment by njustesen** [comment]
Interesting. We are actually doing some refactoring of get_tackle_zones_detailed_at(). I will push it very soon. It will be interesting to see how it affects the performance of grodbot.

**Comment by njustesen** [comment]
This is in fact implemented as there is a ParetoFront object stored for each square in range. We just need to add an option to the pathfinding API that returns these rather than the safest path.
