### ISSUE TITLE
Decouple bots from the game engine stack

### ISSUE THREAD

**Issue by danj3000** [njustesen/ffai#85]
Procbots and grodbot are tightly coupled to the game procedure stack in order to determine what's going on in the game.

They do this by directly using game.state.stack.peek() to get the last procedure in the stack.

This kind of deep access is limiting how the game engine can be changed, and specifically prevents the introduction of procedures that don't directly reflect the current action of the game 

e.g. reroll or 'opponent input' procedures could both be created as part of an overall block game action, but do not themselves indicate that a block is taking place.

I suggest replacing access to the game stack with a method on Game that can walk the stack to determine the relevant procedure to return - ideally as an enum value. Any new generic procedure would be flagged so as to be skipped in the process.

**Comment by njustesen** [comment]
I like the idea of having a method on Game instead of inspecting the stack. However, introducing enums that are 99% similar to the classes implementing Procedure seems redundant. 

What would this new function return e.g. during a Dodge procedure if Reroll is added to the stack? Should the Agent see that the current procedure is Dodge or Reroll?

**Comment by danj3000** [comment]
I think for your example the bot needs to know the overall context - Dodge. The fact that it failed and is a reroll choice is implied by the available actions.

Regarding the use of classes or enums - I admit that it is more code for seemingly little benefit, but if I were designing an interface on Game from scratch I don't think I'd choose to return the actual objects on the stack rather than a string/enum/whatever to identify the domain meaning. This isn't 100% necessary at this stage though, so I'll put together a PR using the current proof approach.

**Comment by njustesen** [comment]
Great. 

I agree that passing Procedure sub-classes is a weird way to inform about the stage of the game. The idea behind the ProcBot was to hide this complexity by overriding methods instead. In fact, the ProcBot should be the standard way of implementing a scripted bot in FFAI. Maybe it should be called something more user-friendly.
