### ISSUE TITLE
Apothecary code incorrect

### ISSUE THREAD

**Issue by danj3000** [njustesen/ffai#90]
The code for apothecary appears to allow you to choose the first or second dice roll.
There is a comment that it doesn't work properly, but this is also not per the rules, where the second roll must be accepted if made.
need to add tests + clean up

**Comment by njustesen** [comment]
Which rulebook do you refer to?
Living Rulebook 6: 

> Otherwise immediately after the player suffers the Casualty, you can use the Apothecary to make your opponent roll again on the Casualty table and then **you** choose which of the two results to apply.

I think the UI needs to be improved when selecting the first or second roll. I haven't tested this at all.

**Comment by danj3000** [comment]
Your right, it's my mistake - I thought it wasn't a choice. I also just checked my DZ1 and it's a choice of the 2. Closing the issue.
